name: Svelte-Check

on:
  pull_request:

jobs:
  svelte-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Svelte Check
        run: npm run check
